# Generated by Django 3.2.7 on 2023-09-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='host',
        ),
    ]
