# Generated by Django 3.2.7 on 2023-09-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='unknown',
            field=models.CharField(blank=True, default='Unknown', max_length=250, null=True),
        ),
    ]
