# Generated by Django 3.2.7 on 2023-09-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_unknown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='unknown',
            field=models.CharField(blank=True, default='Nothing', max_length=250, null=True),
        ),
    ]
