# Generated by Django 3.2.7 on 2023-09-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230905_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='unknown',
        ),
        migrations.AddField(
            model_name='blog',
            name='classes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
