# Generated by Django 3.2.7 on 2023-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
