# Generated by Django 3.2.7 on 2023-09-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='size',
        ),
    ]
