# Generated by Django 3.2.7 on 2023-09-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_cart_order_wishist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='wishist',
            old_name='products',
            new_name='books',
        ),
    ]
