# Generated by Django 3.2.7 on 2023-09-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='cartbooks', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='wishist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='wishlistbooks', to='books.Book'),
        ),
    ]
