# Generated by Django 3.2.7 on 2023-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20230902_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
