# Generated by Django 3.2.7 on 2023-09-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
