# Generated by Django 3.2.7 on 2023-09-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_remove_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
