# Generated by Django 3.2.7 on 2023-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20230902_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
