# Generated by Django 3.2.7 on 2023-09-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20230902_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
