# Generated by Django 3.2.7 on 2023-09-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='emali',
            field=models.EmailField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
