# Generated by Django 3.2.7 on 2023-09-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20230903_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='emali',
            new_name='email',
        ),
    ]
