# Generated by Django 3.2.7 on 2023-09-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_rename_emali_review_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
