# Generated by Django 3.2.7 on 2023-09-08 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.classe'),
        ),
    ]
