# Generated by Django 3.2.7 on 2023-09-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_alter_classe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
