# Generated by Django 3.2.7 on 2023-09-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ship_different',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='books.cart'),
        ),
    ]
