# Generated by Django 3.2.7 on 2023-09-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_auto_20230919_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_by',
            new_name='user',
        ),
    ]
