# Generated by Django 3.2.7 on 2023-09-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0044_alter_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_order',
        ),
    ]
